name: update-qa-after-release
on: 
  pull_request:
    types:
     - opened
    branches: 
     - master
jobs:
  update-qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.email "living2snowboard@gmail.com"
      - run: git config --global user.name "WyldWanderer"
      - run: git fetch --all
      - run: git checkout qa
      - run: git merge
      - run: git merge --ff-only origin/master --allow-unrelated-histories
      - run: git push 
        

    