name: update-qa-after-release
on: [push]
jobs:
  update-qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: master
      - run: | 
          git fetch --all
          git checkout qa
          git merge --ff-only origin/main
          git push 

    