name: update-qa-after-release
on:
  push:
    branches: [ master ]
jobs:
  update-qa:
    runs-on: ubuntu-latest
    steps:
    - name: Install git
      run: |
        apt-get install -y git
        git --version
        echo "Path is ... $PATH"
        PATH=$PATH:$(which git)
        echo "Path is ... $PATH"
    - name: Update QA
        run: | 
          git checkout master
          git fetch --all
          git checkout qa
          git merge --ff-only origin/main
          git push 

    